Entity/Image.php
<?php

namespace ATM\OrderTrackerBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use \DateTime;

/**
 * @ORM\Entity
 * @ORM\Table(name="atm_image")
 */
class Image
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(name="path", type="string", length=255, nullable=false)
     */
    private $path;

    /**
     * @ORM\Column(name="creation_date", type="datetime", nullable=false)
     */
    private $creation_date;

    /**
     * @ORM\ManyToOne(targetEntity="Product", inversedBy="images")
     */
    protected $product;

    /**
     * @ORM\Column(name="position", type="integer", nullable=true)
     */
    private $position;

    /**
     * @ORM\Column(name="is_main", type="boolean", nullable=false)
     */
    private $isMain;

    public function __construct(){
        $this->creation_date = new DateTime();
        $this->position = 0;
        $this->isMain = false;
    }

    public function getId()
    {
        return $this->id;
    }

    public function getPath()
    {
        return $this->path;
    }

    public function setPath($path)
    {
        $this->path = $path;
    }

    public function getCreationDate()
    {
        return $this->creation_date;
    }

    public function setCreationDate($creation_date)
    {
        $this->creation_date = $creation_date;
    }

    public function getProduct()
    {
        return $this->product;
    }

    public function setProduct($product)
    {
        $this->product = $product;
    }

    public function getPosition()
    {
        return $this->position;
    }

    public function setPosition($position)
    {
        $this->position = $position;
    }

    public function getIsMain()
    {
        return $this->isMain;
    }

    public function setIsMain($isMain)
    {
        $this->isMain = $isMain;
    }
}

Resources/views/Admin/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <title>Order Tracker Bundle</title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="Distribution" content="Global" />
        <meta name="Rating" content="Mature" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{{ asset('bundles/atmordertracker/fonts/lato.css') }}" type="text/css"/>
        <link rel="stylesheet" href="{{ asset('bundles/atmordertracker/fonts/quicksand.css') }}" type="text/css"/>
        <link rel="stylesheet" href="{{ asset('bundles/atmordertracker/fonts/leaguespartan.css') }}" type="text/css"/>
        <link rel="stylesheet" href="{{ asset('bundles/atmordertracker/css/font-awesome/css/font-awesome.min.css') }}" type="text/css"/>
        <link rel="stylesheet" href="{{ asset('bundles/atmordertracker/plugins/bootstrap/modal/modal.css') }}" type="text/css"/>
        <link rel="stylesheet" href="{{ asset('bundles/atmordertracker/css/jquery-ui.css') }}">
        <script type="text/javascript" src="{{ asset('bundles/fosjsrouting/js/router.js') }}"></script>
        <script type="text/javascript" src="{{ path('fos_js_routing_js', {"callback": "fos.Router.setData"}) }}"></script>
        <link href="{{ asset('bundles/atmordertracker/css/css.css') }}" rel="stylesheet">
        <script src="{{ asset('bundles/atmordertracker/js/jquery-1112.js') }}"></script>
        {% block atm_ot_stylesheets %}{% endblock atm_ot_stylesheets %}
        {% block atm_ot_headingJS %}{% endblock atm_ot_headingJS %}
    </head>
    <body class="atm_order_tracker">
        <div class="inner body">
            {% block atm_ot_menu %}
            <div class="menu">
                <ul>
                    {% set dates = getDateByRangeName('current_month') %}
                    <li><a href="{{ path('atm_ot_index',{ 'initDate':dates.initDate,'endDate':dates.endDate }) }}">Order Tracker Admin</a></li>
                    <li><a href="{{ path('atm_ot_create_product') }}">Create Product</a></li>
                    <li><a href="{{ path('atm_ot_product_list') }}">Products List</a></li>
                    <li><a href="{{ path('atm_ot_list_shipping_addresses') }}">Shipping Addresses</a></li>
                    <li><a href="{{ path('atm_ot_manage_countries') }}">Manage Countries</a></li>
                </ul>
                <div class="clear"></div>
            </div>
            {% endblock atm_ot_menu %}
            {% block atm_ot_content %}{% endblock atm_ot_content %}
        </div>
        {% block atm_ot_popups %}
            <div class="modal fade" id="popPurchaseDetails" tabindex="-1" role="dialog"  aria-hidden="true">
                <div class="modal-dialog" role="document" style="max-width: 800px;">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h1 style="font-weight: bold;">Purchase Details</h1>
                            <a class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">X</span>
                            </a>
                        </div>
                        <div class="modal-body" id="purchase_details_container"></div>
                    </div>
                </div>
            </div>

            <div class="modal fade" id="popPurchaseSent" tabindex="-1" role="dialog"  aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h1 style="font-weight: bold;">Upload a picture for the purchase</h1>
                            <a class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">X</span>
                            </a>
                        </div>
                        <form action="" method="post" enctype="multipart/form-data" id="frmPurchaseSent">
                            <img src="{{ asset('bundles/atmordertracker/images/image-placeholder.png') }}" id="imgPurchasePreview">
                            <input type="file" name="purchaseImage" id="purchaseImage">
                            <input type="hidden" name="url" id="txRedirectUrl"><br>
                            <input type="text" id="txSendDate" name="txSendDate" autocomplete="off" style="margin-top: 20px;">
                            <input type="submit" class="but blue" value="Upload">
                        </form>
                    </div>
                </div>
            </div>
        {% endblock atm_ot_popups %}

        {% block atm_ot_javascripts %}
            <script src="{{ asset('bundles/atmordertracker/plugins/bootstrap/modal/modal.js') }}"></script>
            <script src="{{ asset('bundles/atmordertracker/plugins/bootstrap/modal/bootstrap.bundle.js') }}"></script>
            <script src="{{ asset('bundles/atmordertracker/js/jquery-ui.min.1121.js') }}"></script>
            <script>
                $('#txSendDate').datepicker({
                    dateFormat: 'dd-mm-yy'
                });
                $('#slcPurchasesType').change(function(){
                    var url = $(this).val();
                    location.href = url;
                });

                $('#btnSearchRange').click(function(){
                    var initYear = $('#initYear').val();
                    var initMonth = $('#initMonth option:selected').val();
                    var initDate = initYear + '-' + initMonth + '-01';

                    var endYear = $('#endYear').val();
                    var endMonth = $('#endMonth option:selected').val();
                    var endDays = $('#endMonth option:selected').attr('data-days');
                    var endDate = endYear + '-' + endMonth + '-' + endDays;

                    window.location.href= Routing.generate('atm_ot_index',{ 'initDate':initDate, 'endDate':endDate, 'sent':{{ sent is defined ? sent : 0  }} });
                });

                $('.see_purchase').click(function(){
                    var purchaseId = $(this).attr('data-purchase-id');

                    $.ajax({
                        url: Routing.generate('atm_ot_purchase_details',{ 'purchaseId':purchaseId }),
                        type: 'post',
                        dataType: 'html',
                        success: function(data){
                            $('#purchase_details_container').html(data);
                            $('#popPurchaseDetails').modal('show');
                        }
                    });
                });

                $('#purchaseImage').on('change', function() {
                    var currentInput = $(this);
                    var file = currentInput[0].files[0];

                    var reader = new FileReader();
                    reader.onload = function(e){
                        $('#imgPurchasePreview').attr('src', e.target.result);
                    };
                    reader.readAsDataURL(file);
                });


            </script>
        {% endblock atm_ot_javascripts %}
    </body>
</html>

Resources/views/Admin/countries.html.twig
{% extends 'ATMOrderTrackerBundle:Admin:base.html.twig'%}

{% block atm_ot_content %}
    <div class="country_tabs">
        <table>
            <tr>
                {% for l in 'A'..'Z' %}
                    <td>
                        <a href="{{ path('atm_ot_manage_countries',{ 'letter':l }) }}" {{ letter == l ? 'style="font-weight:bold"' }}>{{ l }}</a>
                    </td>
                {% endfor %}
            </tr>
        </table>
    </div>
    <table id="tblCountries">
        <thead>
            <tr>
                <th>Name</th>
                <th>Code</th>
                <th>Phone Number</th>
                <th>Hidden</th>
            </tr>
        </thead>
        <tbody>
            {% for country in countries %}
                <tr>
                    <td>
                        {{ country.name }}
                    </td>
                    <td>
                        {{ country.code }}
                    </td>
                    <td>
                        {{ country.phoneCode }}
                    </td>
                    <td>
                        {{ country.hidden ? ('<i data-country-id="'~ country.id ~'" class="fa fa-check"></i>')| raw : ('<i data-country-id="'~ country.id ~'" class="fa fa-times"></i>')| raw }}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock atm_ot_content %}

{% block atm_ot_javascripts %}
    <script>
        $('.fa').click(function(){
            var btn = $(this);
            var countryId = btn.attr('data-country-id');

            $.ajax({
                url: Routing.generate('atm_ot_manage_countries_visibility',{ 'countryId':countryId }),
                type: 'post',
                success: function(data){
                    if(data == 1){
                        btn.removeClass('fa-times').addClass('fa-check');
                    }else{
                        btn.removeClass('fa-check').addClass('fa-times');
                    }
                }
            });
        });
    </script>
{% endblock atm_ot_javascripts %}

Resources/views/Admin/edit_shipping_address.html.twig
{% extends 'ATMOrderTrackerBundle:Admin:base.html.twig'%}


{% block atm_ot_content %}
    <div class="wide" style="display:block">
        <form action="{{ path('atm_ot_edit_shipping_address',{'shippingAddressId':shippingAddressId}) }}" method="post">
            <fieldset>
                {{ form_widget(form.first_name) }}
            </fieldset>
            <fieldset>
                {{ form_widget(form.last_name) }}
            </fieldset>
            <fieldset>
                {{ form_widget(form.email) }}
            </fieldset>
            <fieldset>
                {{ form_widget(form.address) }}
            </fieldset>
            <fieldset>
                {{ form_widget(form.city) }}
            </fieldset>
            <fieldset>
                {{ form_widget(form.state) }}
            </fieldset>
            <fieldset>
                {{ form_widget(form.zipCode) }}
            </fieldset>
            <fieldset>
                <div class="selectC" style="width: 100%;">
                    {{ form_widget(form.country,{ 'attr':{ 'style':'width:100%' } }) }}
                </div>
            </fieldset>
            <fieldset>
                {{ form_widget(form.phone) }}
            </fieldset>

            <fieldset>
                {{ form_widget(form.delivery_instructions) }}
            </fieldset>
            {{ form_rest(form) }}
            <input type="submit" id="_sb_shipping_address" style="display: none;">
            <a class="but blue" onclick="$('#_sb_shipping_address').click();">Save</a>
        </form>
    </div>
{% endblock %}

Resources/views/Admin/filters.html.twig
<div class="wide datePicker">
    <div class="half">
        Select a period of time
        <div class="clear"></div>
        {% set currentMonthDates = getDateByRangeName('current_month') %}
        <a class="butPeriod but blue" href="{{ path('atm_ot_index',{ 'initDate':currentMonthDates.initDate,'endDate':currentMonthDates.endDate,'sent':sent,'onlyGifts': onlyGifts }) }}">This Month</a>
        {% set lastMonthDates = getDateByRangeName('last_month') %}
        <a class="butPeriod but blue" href="{{ path('atm_ot_index',{ 'initDate':lastMonthDates.initDate,'endDate':lastMonthDates.endDate,'sent':sent,'onlyGifts': onlyGifts }) }}">Last Month</a>
        {% set lastYearDates = getDateByRangeName('current_year') %}
        <a class="butPeriod but blue" href="{{ path('atm_ot_index',{ 'initDate':lastYearDates.initDate,'endDate':lastYearDates.endDate,'sent':sent,'onlyGifts': onlyGifts }) }}">This Year</a>
    </div>
    <div class="half">
        <div class="half">
            From this date
            <div class="clear"></div>
            <div class="selectC">
                <select placeholder="Year" id="initYear">
                    {% for year in yearsFilter %}
                        {% set selected = '' %}
                        {% if year == initDateTokens[0] %}
                            {% set selected = 'selected="selected"' %}
                        {% endif %}
                        <option {{ selected | raw }} value="{{ year }}">{{ year }}</option>
                    {% endfor %}
                </select>
            </div>
            {% set months = ['January','February','March','April','May','June','July','August','September','October','November','December'] %}
            {% set monthsNumbers = ['01','02','03','04','05','06','07','08','09','10','11','12'] %}
            <div class="selectC">
                <select placeholder="Month" id="initMonth">
                    {% for month in months %}
                        {% set selected = '' %}
                        {% if monthsNumbers[loop.index0] == initDateTokens[1] %}
                            {% set selected = 'selected="selected"' %}
                        {% endif %}
                        <option {{ selected | raw }} value="{{ monthsNumbers[loop.index0] }}">{{ month }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="half">
            To this date
            <div class="clear"></div>
            <div class="selectC">
                <select placeholder="Year" id="endYear">
                    {% for year in yearsFilter %}
                        {% set selected = '' %}
                        {% if year == initDateTokens[0] %}
                            {% set selected = 'selected="selected"' %}
                        {% endif %}
                        <option {{ selected | raw }} value="{{ year }}">{{ year }}</option>
                    {% endfor %}
                </select>
            </div>
            {% set monthsNumberDays = ['31','28','31','30','31','30','31','31','30','31','30','31'] %}
            <div class="selectC">
                <select placeholder="Month" id="endMonth">
                    {% for month in months %}
                        {% set selected = '' %}
                        {% if monthsNumbers[loop.index0] == endDateTokens[1] %}
                            {% set selected = 'selected="selected"' %}
                        {% endif %}
                        <option {{ selected | raw }} data-days="{{ monthsNumberDays[loop.index0] }}" value="{{ monthsNumbers[loop.index0] }}">{{ month }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="wide centerBut"><a class="but blue" id="btnSearchRange">Search</a></div>
    </div>
    <div class="clear"></div>
</div>
<div class="wide">
    <h2 class="block_title statsTitle">
        <div>
            <em class="small">From:</em>
            <div class="clear"></div>
            {{ initPeriod | date('d-m-Y') }}
        </div>
        <div>
            <em class="small">To:</em>
            <div class="clear"></div>
            {{ endPeriod | date('d-m-Y') }}
        </div>
        {% if users is defined %}
            <div class="flex usersSelect" style="margin-top: 13px;float: right;font-weight: normal;">
                <span>Historical of:</span>
                <div class="selectC" style="">
                    <select id="slcHistorical" onchange="location.href = Routing.generate('atm_ot_historical',{ 'userId':$(this).val() })">
                        <option value="--">--</option>
                        {% for user in users %}
                            {% set selected = '' %}
                            {% if userId is defined and userId == user.id %}
                                {% set selected = 'selected=selected' %}
                            {% endif %}
                            <option value="{{ user.id }}" {{ selected | raw }}>{{ user.username }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
        {% endif %}
        <div class="flex" style="margin: 18px 0 0 33px;float: left;font-weight: normal;">
            <label>
                <input type="checkbox" id="_chk_gifts" {{ onlyGifts == 1 ? 'checked' }}>
                Show only gifts
            </label>
        </div>
        <div class="flex usersSelect" style="margin-top: 13px;float: right;font-weight: normal;margin-right: 20px;">
            <span>Showing: </span>
            <div class="selectC" style="">
                <select id="slcPurchasesType">
                    <option value="{{ path('atm_ot_index', { 'initDate': initDate ,'endDate': endDate,'sent': 1,'onlyGifts': onlyGifts }) }}" {{ sent ? 'selected="selected"' }}>Sent purchases</option>
                    <option value="{{ path('atm_ot_index', { 'initDate': initDate ,'endDate': endDate,'sent': 0,'onlyGifts': onlyGifts }) }}" {{ not sent ? 'selected="selected"' }}>Pending purchases</option>
                </select>
            </div>
        </div>
    </h2>
    <div class="clear"></div>
</div>

Resources/views/Admin/gift_historical.html.twig
{% extends 'ATMOrderTrackerBundle:Admin:base.html.twig'%}


{% block atm_ot_content %}
    {% include 'ATMOrderTrackerBundle:Admin:filters.html.twig' with {
        'initDateTokens':initDateTokens,
        'endDateTokens':endDateTokens,
        'yearsFilter':yearsFilter,
        'initPeriod':initPeriod,
        'endPeriod':endPeriod,
        'sent' : 0,
        'userId' : userId,
        'onlyGifts': 0
    } %}
    <div class="wide" style="display:block">
        <div class="stats">

            <div id="purchasesContainer">
                {{ render(controller('ATMOrderTrackerBundle:Admin:searchPurchases',{
                    'initDate' : null,
                    'endDate' : null,
                    'sent': null,
                    'page': page,
                    'userId' : null,
                    'giftedTo': giftedTo
                })) }}
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
        </div>
    </div>
{% endblock atm_ot_content %}

{% block atm_ot_javascripts %}
    {{ parent() }}
    <script>
        $('.set_as_sent').click(function(){
            var purchaseId = $(this).attr('data-purchase-id');

            $('#frmPurchaseSent').attr('action',Routing.generate('atm_ot_purchase_set_send',{ 'purchaseId':purchaseId }));
            $('#txRedirectUrl').val(Routing.generate('atm_ot_gift_historical',{ 'giftedTo':{{ giftedTo }},'page':{{ page }} }));
            $('#popPurchaseSent').modal('show');
        });

        $('#_chk_gifts').change(function(){
            location.href = Routing.generate('atm_ot_historical',{ 'userId':'{{ userId }}', 'onlyGifts': 0 });
        });
    </script>
{% endblock atm_ot_javascripts %}

Resources/views/Admin/historical.html.twig
{% extends 'ATMOrderTrackerBundle:Admin:base.html.twig'%}


{% block atm_ot_content %}
    {% include 'ATMOrderTrackerBundle:Admin:filters.html.twig' with {
        'initDateTokens':initDateTokens,
        'endDateTokens':endDateTokens,
        'yearsFilter':yearsFilter,
        'initPeriod':initPeriod,
        'endPeriod':endPeriod,
        'sent' : 0,
        'userId' : userId,
        'onlyGifts': 0
    } %}
    <div class="wide" style="display:block">
        <div class="stats">

            <div id="purchasesContainer">
                {{ render(controller('ATMOrderTrackerBundle:Admin:searchPurchases',{
                    'initDate' : null,
                    'endDate' : null,
                    'sent': null,
                    'page': page,
                    'userId' : userId
                })) }}
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
        </div>
    </div>
{% endblock atm_ot_content %}

{% block atm_ot_javascripts %}
    {{ parent() }}
    <script>
        $('.set_as_sent').click(function(){
            var purchaseId = $(this).attr('data-purchase-id');

            $('#frmPurchaseSent').attr('action',Routing.generate('atm_ot_purchase_set_send',{ 'purchaseId':purchaseId }));
            $('#txRedirectUrl').val(Routing.generate('atm_ot_historical',{ 'userId':{{ userId }},'page':{{ page }} }));
            $('#popPurchaseSent').modal('show');
        });

        $('#_chk_gifts').change(function(){
            let onlyGifts = $(this).is(':checked') ? 1 : 0;
            location.href = Routing.generate('atm_ot_historical',{ 'userId':'{{ userId }}', 'onlyGifts': 0 });
        });
    </script>
{% endblock atm_ot_javascripts %}

Resources/views/Admin/index.html.twig
{% extends 'ATMOrderTrackerBundle:Admin:base.html.twig'%}

{% block atm_ot_content %}
    {% include 'ATMOrderTrackerBundle:Admin:filters.html.twig' with {
        'initDateTokens':initDateTokens,
        'endDateTokens':endDateTokens,
        'yearsFilter':yearsFilter,
        'initPeriod':initPeriod,
        'endPeriod':endPeriod,
        'sent' : sent,
        'onlyGifts': onlyGifts
    } %}
    <div class="wide" style="display:block">
        <div class="stats">
            <div id="purchasesContainer">
                {{ render(controller('ATMOrderTrackerBundle:Admin:searchPurchases',{
                    'initDate' : initDate,
                    'endDate' : endDate,
                    'sent': sent,
                    'onlyGifts': onlyGifts == 1 ? true:false,
                    'page': page
                })) }}
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
        </div>
    </div>
{% endblock atm_ot_content %}

{% block atm_ot_javascripts %}
    {{ parent() }}
    <script>
        $('.set_as_sent').click(function(){
            var purchaseId = $(this).attr('data-purchase-id');

            $('#frmPurchaseSent').attr('action',Routing.generate('atm_ot_purchase_set_send',{ 'purchaseId':purchaseId }));
            $('#txRedirectUrl').val(Routing.generate('atm_ot_index',{ 'initDate':'{{ initDate }}','endDate':'{{ endDate }}','sent':{{ sent }},'page':{{ page }}, 'onlyGifts': {{ onlyGifts }} }));
            $('#popPurchaseSent').modal('show');
        });

        $('#_chk_gifts').change(function(){
            let onlyGifts = $(this).is(':checked') ? 1 : 0;
            location.href = Routing.generate('atm_ot_index',{ 'initDate':'{{ initDate }}','endDate':'{{ endDate }}','sent':{{ sent }},'page':{{ page }}, 'onlyGifts': onlyGifts });
        });
    </script>
{% endblock atm_ot_javascripts %}

Resources/views/Admin/purchase_details.html.twig
<div class="purchase_details">
    <div class="wide" style="border-bottom: 1px solid #000;box-sizing: border-box;">
        <h1>Destination Address</h1>
        <ul>
            {% if purchase.giftedTo %}
                {% set shippingAddress = ATMOrderTrackerGetUserShippingAddress(purchase.giftedTo.id) %}
                <li><span>Username: </span>{{ shippingAddress.user.username | title }}</li>
                <li><span>Address: </span>{{ shippingAddress.address }}</li>
                <li><span>Real name: </span>{{ shippingAddress.first_name | title }} {{ shippingAddress.last_name }}</li>
                <li><span>City: </span>{{ shippingAddress.city }}</li>
                <li><span>Email: </span>{{ shippingAddress.email }}</li>
                <li><span>Zip Code: </span>{{ shippingAddress.zipCode }}</li>
                <li><span>Phone Number: </span>{{ shippingAddress.phone }}</li>
                {% if shippingAddress.state %}
                    <li><span>State: </span>{{ shippingAddress.state }}</li>
                {% endif %}
                {% if shippingAddress.country %}
                    <li style="width: 50%;float: right;"><span>Country: </span>{{ shippingAddress.country.name }}</li>
                {% endif %}
            {% else %}
                <li><span>Username: </span>{{ purchase.user.username | title }}</li>
                <li><span>Address: </span>{{ purchase.address }}</li>
                <li><span>Real name: </span>{{ purchase.first_name | title }} {{ purchase.last_name }}</li>
                <li><span>City: </span>{{ purchase.city }}</li>
                <li><span>Email: </span>{{ purchase.email }}</li>
                <li><span>Zip Code: </span>{{ purchase.zipCode }}</li>
                <li><span>Phone Number: </span>{{ purchase.phoneNumber }}</li>
                {% if purchase.state %}
                    <li><span>State: </span>{{ purchase.state }}</li>
                {% endif %}
                {% if purchase.country %}
                <li style="width: 50%;float: right;"><span>Country: </span>{{ purchase.country.name }}</li>
                {% endif %}
            {% endif %}
        </ul>
        <div class="clear"></div>
    </div>
    <div class="wide product_list_details">
        <table>
            <thead>
                <tr>
                    <th>Product Name</th>
                    <th style="text-align: center;">Price</th>
                </tr>
            </thead>
            <tbody>
                {% for product in purchase.purchasedProductSizes %}
                    <tr>
                        <td>
                            {{ product.productName }} {{ product.size is not null ? (' <span style="font-weight:normal">size:</span> '~ product.size.name) | raw }}
                        </td>
                        <td style="text-align: center;">
                            {{ product.price > 0 ? product.price | number_format ~ ' points'  : product.tokens | number_format ~ ' tokens'  }}
                        </td>
                    </tr>
                {% endfor %}
                <tr>
                    <td class="total_label">Total:</td>
                    {% if purchase.giftedTo %}
                        <td class="total_price">{{ purchase.total | number_format ~ ' tokens' }}</td>
                    {% else %}
                        <td class="total_price">{{ purchase.total | number_format ~ ' points' }}</td>
                    {% endif %}

                </tr>
            </tbody>
        </table>
    </div>
    <div class="clear"></div>
    <div class="wide">
        <a class="but red" style="display: inline-block;margin: 20px auto;float: none;" onclick="$('#popPurchaseDetails').modal('hide')">Close</a>
    </div>
</div>

Resources/views/Admin/purchases_table.html.twig
{% if purchases | length > 0 %}
    <table>
        <thead>
            <tr>
                <th>
                    Send Date
                </th>
                <th>
                    Order Date
                </th>
                <th>
                    User
                </th>
                <th>
                    Gifted To
                </th>
                <th>
                    Total
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for purchase in purchases %}
                {% include 'ATMOrderTrackerBundle:Admin/item:purchase.html.twig' with { 'purchase' : purchase } %}
            {% endfor %}
        </tbody>
    </table>
    {% if pagination is not null %}
        <div class="navigation">
            {{ knp_pagination_render(pagination) }}
        </div>
    {% endif %}
{% else %}
    <div class="no_results">No purchases to show</div>
{% endif %}

Resources/views/Admin/shipping_addresses.html.twig
{% extends 'ATMOrderTrackerBundle:Admin:base.html.twig'%}


{% block atm_ot_content %}
    {% include 'ATMOrderTrackerBundle:Admin:filters.html.twig' with {
        'initDateTokens':initDateTokens,
        'endDateTokens':endDateTokens,
        'yearsFilter':yearsFilter,
        'initPeriod':initPeriod,
        'endPeriod':endPeriod,
        'sent' : 0,
        'userId' : null,
        'onlyGifts': 0
    } %}
    <div class="wide" style="display:block">
        <div class="stats">
            <table>
                <thead>
                    <tr>
                        <th>Username</th>
                        <th>Creation date</th>
                        <th>Approved</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                {% for shipping_address in shipping_addresses %}
                <tr>
                    <td>
                        {{ shipping_address.user.title ? shipping_address.user.title : shipping_address.user.username }}
                    </td>
                    <td>
                        {{ shipping_address.creationDate | date('d-m-Y') }}
                    </td>
                    <td>
                        {{ shipping_address.approved ? '<i class="fa fa-check" style="color: #00ff08;font-size: 20px;"></i>' : '<i class="fa fa-times" style="color:#ea0000;font-size: 20px;"></i>' }}
                    </td>
                    <td>
                        <a href="{{ path('atm_ot_edit_shipping_address',{ 'shippingAddressId':shipping_address.id }) }}" style="font-size: 20px;display: inline-block;margin-right: 10px;"><i class="fa fa-edit"></i></a>
                        <a href="{{ path('atm_ot_delete_shipping_address',{ 'shippingAddressId':shipping_address.id }) }}" style="font-size: 20px;display: inline-block"><i class="fa fa-times"></i></a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
            <div class="clear"></div>
        </div>
        <div class="clear"></div>
    </div>
{% endblock %}